name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: appleboy/ssh-action@v0.1.4
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        script: | 
          cd /home/ubuntu/seller-api
          git pull
          pkill -f gunicorn
          cd /home/ubuntu/seller-api/api
          gunicorn --bind 0:8000 main:app --worker-class uvicorn.workers.UvicornWorker